name: puddingku_smart_system
description: A new Flutter project.

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/