name: puddingku_smart_system
description: A new Flutter project.

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/