// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77Y3SGtfJG_RRgluCA7JBXpBtkq0ynoY',
    appId: '1:805635807464:web:f044b5ef9f3c57522f915d',
    messagingSenderId: '805635807464',
    projectId: 'puddingku-87c27',
    authDomain: 'puddingku-87c27.firebaseapp.com',
    storageBucket: 'puddingku-87c27.firebasestorage.app',
    measurementId: 'G-JLYJG53D0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ib2QPVfSzUPcSZKXg19xz8vf_tvDX_w',
    appId: '1:805635807464:android:4aac366f21ea41ad2f915d',
    messagingSenderId: '805635807464',
    projectId: 'puddingku-87c27',
    storageBucket: 'puddingku-87c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLQnycQBWX_UVVuv1IfCNJQeM53Rj_dw',
    appId: '1:805635807464:ios:4a54b451f5ff79772f915d',
    messagingSenderId: '805635807464',
    projectId: 'puddingku-87c27',
    storageBucket: 'puddingku-87c27.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLQnycQBWX_UVVuv1IfCNJQeM53Rj_dw',
    appId: '1:805635807464:ios:4a54b451f5ff79772f915d',
    messagingSenderId: '805635807464',
    projectId: 'puddingku-87c27',
    storageBucket: 'puddingku-87c27.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA77Y3SGtfJG_RRgluCA7JBXpBtkq0ynoY',
    appId: '1:805635807464:web:537ef5d392f5628b2f915d',
    messagingSenderId: '805635807464',
    projectId: 'puddingku-87c27',
    authDomain: 'puddingku-87c27.firebaseapp.com',
    storageBucket: 'puddingku-87c27.firebasestorage.app',
    measurementId: 'G-RFG1NLVJQP',
  );
}
